-- MySQL Script generated by MySQL Workbench
-- Sat Dec 30 15:28:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Day` (
  `id_day` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id_day`));


-- -----------------------------------------------------
-- Table `mydb`.`Job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Job` (
  `id_job` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `job_name` VARCHAR(55) NOT NULL,
  `possible_groupwork` TINYINT NOT NULL,
  `salary` INT NOT NULL,
  `workhour_per_day` INT NOT NULL,
  PRIMARY KEY (`id_job`));


-- -----------------------------------------------------
-- Table `mydb`.`Person_Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person_Data` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `second_name` VARCHAR(45) NOT NULL,
  `place_of_residence` VARCHAR(55) NOT NULL,
  `sex` VARCHAR(45) NOT NULL,
  `family` TINYINT NOT NULL,
  `kids_quantity` INT NOT NULL,
  `job` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX (`job` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`job`)
    REFERENCES `mydb`.`Job` (`id_job`));


-- -----------------------------------------------------
-- Table `mydb`.`Statistic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Statistic` (
  `day` INT UNSIGNED NOT NULL,
  `person` INT UNSIGNED NOT NULL,
  `completed_tasks` INT NOT NULL,
  `failed_tasks` INT NOT NULL,
  `work_time` TIME NOT NULL,
  `sucess_percent` INT NOT NULL,
  INDEX (`day` ASC) VISIBLE,
  INDEX (`person` ASC) VISIBLE,
  CONSTRAINT `fk_day`
    FOREIGN KEY (`day`)
    REFERENCES `mydb`.`Day` (`id_day`),
  CONSTRAINT `fk_person`
    FOREIGN KEY (`person`)
    REFERENCES `mydb`.`Person_Data` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Category_of_Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category_of_Task` (
  `id_category` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `from_who_task` INT UNSIGNED NOT NULL,
  `type` VARCHAR(25) NOT NULL,
  `difficulty` INT NOT NULL,
  `priority` INT NOT NULL,
  `group_work` TINYINT NOT NULL DEFAULT 0,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_category`),
  INDEX (`from_who_task` ASC) VISIBLE,
  CONSTRAINT `fk_from_who_task`
    FOREIGN KEY (`from_who_task`)
    REFERENCES `mydb`.`Job` (`id_job`));


-- -----------------------------------------------------
-- Table `mydb`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Task` (
  `id_task` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `taskname` VARCHAR(45) NOT NULL,
  `categoty` INT UNSIGNED NOT NULL,
  `oriented_time` TIME NOT NULL,
  `status_of_task` VARCHAR(10) NOT NULL,
  `features` VARCHAR(255) NULL,
  PRIMARY KEY (`id_task`),
  INDEX (`categoty` ASC) VISIBLE,
  CONSTRAINT `fk_categoty`
    FOREIGN KEY (`categoty`)
    REFERENCES `mydb`.`Category_of_Task` (`id_category`));


-- -----------------------------------------------------
-- Table `mydb`.`Plan_Of_The_Day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Plan_Of_The_Day` (
  `day_number` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `person_id` INT UNSIGNED NOT NULL,
  `day_time` DATETIME NOT NULL,
  `task` INT UNSIGNED NOT NULL,
  `oriented_time` INT NOT NULL,
  `status_of_task` VARCHAR(10) NOT NULL,
  INDEX (`day_number` ASC) VISIBLE,
  INDEX (`person_id` ASC) VISIBLE,
  INDEX (`task` ASC) VISIBLE,
  PRIMARY KEY (`day_number`),
  CONSTRAINT `fk_day_number`
    FOREIGN KEY (`day_number`)
    REFERENCES `mydb`.`Day` (`id_day`),
  CONSTRAINT `fk_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`Person_Data` (`id`),
  CONSTRAINT `fk_task`
    FOREIGN KEY (`task`)
    REFERENCES `mydb`.`Task` (`id_task`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
